tools:
  exceptions: https://vchart.sentry.io/issues/                                                     # Sentry for error tracking
  logging: https://betterstack.com/settings/usage/responders?rf=now-30d&rt=now&res=day             # Betterstack for logging and monitoring
  ci: https://github.com/dcsil/vchart-app/actions                                                  # GitHub Actions for continuous integration

services:
  production: https://vchart-app-beta.vercel.app/
  production_dashboard: https://vercel.com/vcharts-projects/vchart-app

docs:
  getting_started: https://github.com/dcsil/vchart-app

commands:
  bootstrap: script/bootstrap
  server:
    dev: npm run dev
    build: npm run build
    start: npm run start
  test: npm run test
  lint: npm run lint
